[package]
name = "cyapi"
version = "0.1.0"
edition = "2018"
workspace = "../"

[lib]
name = "cyapi"
path = "src/lib.rs"

[dependencies]
serialport = {version = "4.0", default-features = false}
num_enum = "0.5"
byteorder = "1.1"
hex = "0.4.3"
log = "0.4"
env_logger = "0.9"
